### ISSUE TITLE
Production build with AoT throws error - Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by naveedahmed1** [IckleChris/ic-datepicker#7] opened 2017-03-26 20:58 UTC
When trying production build with AoT in Angular CLI, it throws the below error:

```
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /node_modules/ic-datepicker/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in /node_modules/ic-datepicker/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in /node_modules/ic-datepicker/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in /node_modules/ic-datepicker/node_modules/@angular/core/index.d.ts, resolving symbol IcDatepickerModule in /node_modules/ic-datepicker/dist/src/ic-datepicker.module.d.ts, resolving symbol IcDatepickerModule in /node_modules/ic-datepicker/dist/src/ic-datepicker.module.d.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
```

I have imported the IcDatepickerModule module like this in my module:

`import { IcDatepickerModule } from 'ic-datepicker/dist';`

If I update the import to the following:

import { IcDatepickerModule } from 'ic-datepicker';

and delete all contents of node_modules\ic-datepicker
and then copy paste the contents of node_modules\ic-datepicker\dist in node_modules\ic-datepicker. It works. Can you please have a look?

**Comment by IckleChris** [comment] 2017-03-26 21:13
I'm looking into the build issues now but it's going to take some research from my side - is this not a duplicate of #3?

**Comment by naveedahmed1** [comment] 2017-03-26 21:18
Yes indeed, I am sorry I just realized.

**Closed as completed** 2017-03-26 21:17 UTC
