### ISSUE TITLE
Reactive form - clear date if null/undefined

### ISSUE THREAD

**Issue by zzurka** [IckleChris/ic-datepicker#5] opened 2017-03-21 09:11 UTC
In reactive form, if date is null or undefined, it stays on previously selected date. Is it possible to clear date if set date is null or undefined? Thanks

**Comment by naveedahmed1** [comment] 2017-03-21 12:10
I was about to open same issue, in my case the date field always has a default value which is equal to current date even though the date fields are shown as empty on the screen.

I confirmed it by submitting the form without selecting any value and writing form.value to console.

Another related issue is, in my case when the form is submitted I have to store the form.value in a variable in service, because when user opens the details of any item from search list I have to remove search filters from screen and add it back when the user closes the item details page. I repopulate the filters using the filters value stored in service. All other form fields are populated properly . Even the value is assigned to the date fields but its invisible on screen.

**Comment by IckleChris** [comment] 2017-03-25 23:43
Thanks @zzurka this should be fixed in `0.0.7`

**Closed as completed by IckleChris** 2017-03-25 23:43 UTC
